# This workflow performs static analysis checks.
name: verification

on: ["pull_request", "push"]

jobs:
  verification:
    runs-on: macos-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.5.0"

      - name: Install dafny-reportgenerator
        run: dotnet tool install --global dafny-reportgenerator

      - name: Verify Dafny code
        run: |
          SRC_DFYS=`find src -name "*.dfy"`
          TEST_DFYS=`find test -name "*.dfy"`
          dafny /compile:0 /verificationLogger:csv /vcsCores:3 /trace ${SRC_DFYS} ${TEST_DFYS}

      - name: Check durations
        run: dafny-reportgenerator summarize-csv-results --max-duration-seconds 40 TestResults/*.csv
