# This workflow performs static analysis checks.
name: verification

on: ["pull_request", "push"]

jobs:
  verification:
    runs-on: macos-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.5.0"

      - name: Install dafny-reportgenerator
        run: dotnet tool install --global dafny-reportgenerator

      - name: Verify Dafny code
        # Currently, test depends on src, so verifying test will also verify src
        run: dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=2 -p:TestVerifyOverride="verificationLogger:csv" test

      - name: Check durations
        run: dafny-reportgenerator summarize-csv-results --max-duration-seconds 40 test/TestResults/*.csv
